config/routes.rb
ClipsterHost::Application.routes.draw do
  mount Clipster::Engine, :at => '/clipster'
  mount Monologue::Engine, :at => '/blog'
  match "/" => redirect("/blog")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clipster/common/_includes.html.erb
<!-- Insert any HTML here that you wish to include in the <head> of all clipster pages -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29517676-2']);
  _gaq.push(['_setDomainName', 'developerdan.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Developer Dan</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "clipster/application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "clipster/application" %>
  <%= csrf_meta_tags %>
  <%=h yield(:head) %>
  <%= render "clipster/common/includes" %>
</head>
<body class="grayout">
    <div class="container">
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
              <div class="nav-collapse collapse">
                  <%= link_to "Daniel White", "/", :class=>"brand"%>
                  <ul class="nav">
                      <li><%= link_to "Blog", monologue_path %></li>
                      <li><%= link_to "About Me", page_path("about") %></li>
                      <li><%= link_to "Projects", "http://lightswitch05.github.io/" %></li>
                      <li><%= link_to "Clipster", clipster_path %></li>
                      <li><%= link_to "GitHub", "https://github.com/lightswitch05" %></li>
                      <li style="margin-top:10px;margin-left:10px;">
                        <iframe style="border: 0; margin: 0; padding: 0;"
                          src="https://www.gittip.com/lightswitch05/widget.html"
                          width="48pt" height="22pt">
                        </iframe>
                      </li>
                  </ul>
              </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="span12">
          <%= yield %>
      </div>
    </div>
    
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-29517676-2']);
      _gaq.push(['_setDomainName', 'developerdan.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
</body>
</html>

app/views/layouts/monologue/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
  <%= render 'layouts/monologue/application/head' %>
</head>
<body class="grayout">
  <div class="container" style="padding-bottom:50px;">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse">
                <a href="/" class="brand">Daniel White</a>
                <ul class="nav" style="margin: 11px 1px 0 0;">
                    <li><%= link_to "Blog", "/" %>
                    <li><%= link_to "About Me", "/about" %>
                    <li><%= link_to "Projects", "http://lightswitch05.github.io/" %></li>
                    <li><a href="/clipster">Clipster</a></li>
                    <li><a href="https://github.com/lightswitch05">GitHub</a></li>
                    <li style="margin-left: 10px; margin-bottom: 0px;">
                      <iframe style="border: 0; margin: 0; padding: 0;"
                        src="https://www.gittip.com/lightswitch05/widget.html"
                        width="48pt" height="22pt">
                      </iframe>
                    </li>
                </ul>
            </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <header class="main-header sixteen columns clearfix">
      <%= rss_icon %>
      <h1><a href="<%= root_path %>"><%=Monologue.site_name%></a></h1>
      <h2><%=Monologue.site_subtitle%></h2>
      <%= render :partial => "layouts/monologue/application/social_icons" %>
    </header>

    <div class="content twelve columns">
      <% flash.each do |name, msg| %>
        <div class="flash-notice">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>

      <%= render 'layouts/monologue/application/sidebar' %>
  </div>
  <% if content_for?(:footer) %>
    <footer>
      <%= yield :footer %>
    </footer>
  <% end %>
  <%= render 'layouts/monologue/application/disqus' %>
  <%= render 'layouts/monologue/application/gauge_analytics' %>
</body>
</html>

app/views/monologue/posts/_post.html.erb
<% revision = post.active_revision %><section>  <div class="well">      <%= render :partial => 'monologue/posts/revision_header', :locals => {:revision=>revision} %>      <div class="content" data-monologue="content">        <%= truncate_html(revision.content, :length => 1000, :omission => '...') %>      </div>      <div class="tags" data-monologue="tags">        <%= render post.tags %>      </div>      <%= link_to t(".readmore"), revision.full_url, :class => "button" %>  </div></section>

app/views/monologue/posts/_revision_header.html.erb
<header>  <legend><%= link_to revision.title, revision.full_url %></legend>  <div class="posted">    <span data-monologue="time">      <time datetime="<%= revision.published_at %>">        <%= I18n.localize(revision.published_at.to_date, :format => :long) %>      </time>    </span>    <span data-monologue="user">      <%= revision.user.name %>    </span>    <span data-monologue="disqus">      <a href="<%= revision.full_url + "#disqus_thread" %>"></a>    </span>  </div></header>

app/views/monologue/posts/show.html.erb
<% content_for :title do %>  <%= @revision.title %><% end %><% content_for :meta_description do %>  <%= truncate(strip_tags(@revision.content), :length => 155) %><% end %><article>  <div class="well">    <%= render :partial => 'monologue/posts/revision_header', :locals => {:revision=>@revision}%>    <div class="content" data-monologue="content">      <%= raw @revision.content %>    </div>      <div class="tags" data-monologue="tags">      <%= render @revision.post.tags %>    </div>    <%= render "social_sharing" %>    <div id="disqus_thread"></div>    <%= render 'layouts/monologue/application/disqus_embed' %>    <noscript>Please enable JavaScript to view the comments.</noscript>  </div></article>